namespace Un;

public static class Literals
{
    public const string Inf = "inf";
    public const string True = "true";
    public const string False = "false";
    public const string None = "none";
    public const string Null = "null";
    public const string Break = "break";
    public const string Continue = "continue";
    public const string Return = "return";
    public const string Try = "try";
    public const string Catch = "catch";
    public const string Fin = "fin";
    public const string Error = "error";
    public const string Fn = "fn";
    public const string Del = "del";
    public const string Await = "await";
    public const string Async = "async";
    public const string As = "as";
    public const string Using = "using";
    public const string Enum = "enum";
    public const string Class = "class";
    public const string Throw = "throw";
    public const string URL = "URL";
    public const string Comment = "#";
    public const char CComment = '#';
    public const string Is = "is";
    public const string In = "in";
    public const string Import = "import";
    public const string While = "while";
    public const string For = "for";
    public const string Else = "else";
    public const string ElIf = "elif";
    public const string If = "if";
    public const string Func = "func";
    public const string Colon = ":";
    public const char CColon = ':';
    public const string Comma = ",";
    public const char CComma = ',';
    public const string Dot = ".";
    public const char CDot = '.';
    public const string QuestionDot = ".?";
    public const string DoubleQuestion = "??";
    public const string Question = "?";
    public const string RParen = ")";
    public const char CRParen = ')';
    public const string LParen = "(";
    public const char CLParen = '(';
    public const string RBrace = "}";
    public const char CRBrace = '}';
    public const string LBrace = "{";
    public const char CLBrace = '{';
    public const string RBrack = "]";
    public const char CRBrack = ']';
    public const string LBrack = "[";
    public const char CLBrack = '[';
    public const string Equal = "==";
    public const string Unequal = "!=";
    public const string GreaterThen = ">";
    public const char CGreaterThen = '>';
    public const string LessThen = "<";
    public const string GreaterOrEqual = ">=";
    public const string LessOrEqual = "<=";
    public const string DoubleSlash = "//";
    public const string RightShift = ">>";
    public const string LeftShift = "<<";
    public const string Not = "not";
    public const string Or = "or";
    public const string And = "and";
    public const string Xor = "xor";
    public const string Tilde = "~";
    public const string Caret = "^";
    public const string Pipe = "|";
    public const string Amperand = "&";
    public const string Percent = "%";
    public const string Slash = "/";
    public const char CSlash = '/';
    public const string DoubleAsterisk = "**";
    public const string Asterisk = "*";
    public const string Bang = "!";
    public const string Minus = "-";
    public const string Plus = "+";
    public const char CMinus = '-';
    public const char CPlus = '+';
    public const string RightShiftAssign = ">>=";
    public const string LeftShiftAssign = "<<=";
    public const string BXorAssign = "^=";
    public const string BOrAssign = "|=";
    public const string BAndAssign = "&=";
    public const string PercentAssign = "%=";
    public const string DoubleSlashAssign = "//=";
    public const string SlashAssign = "/=";
    public const string DoubleAsteriskAssign = "**=";
    public const string AsteriskAssign = "*=";
    public const string MinusAssign = "-=";
    public const string PlusAssign = "+=";
    public const string Assign = "=";
    public const char CAssign = '=';
    public const string Underbar = "_";
    public const char CUnderbar = '_';

    public const string Self = "self";
    public const string Super = "super";

    public const string Arrow = "=>";

    public const char NewLine = '\n';
    public const char Tab = '\t';
    public const char Backspace = '\b';
    public const char CarriageReturn = '\r';
    public const char FormFeed = '\f';
    public const char VerticalTab = '\v';
    public const char NullChar = '\0';
    public const char Bell = '\a';

    public const char Space = ' ';
    public const char Single = '\'';
    public const char Escape = '\\';
    public const char Double = '"';
    public const char EDouble = '\"';
    public const char Backtick = '`';

    public const string Init = "__init__";
    public const string Add = "__add__";
    public const string Sub = "__sub__";
    public const string Mul = "__mul__";
    public const string Mod = "__mod__";
    public const string Div = "__div__";
    public const string IDiv = "__idiv__";
    public const string Pow = "__pow__";
    public const string LSh = "__lsh__";
    public const string RSh = "__rsh__";
    public const string BAnd = "__band__";
    public const string BOr = "__bor__";
    public const string BXor = "__bxor__";
    public const string BNot = "__bnot__";
    public const string At = "__at__";
    public const string Eq = "__eq__";
    public const string Lt = "__lt__";
    public const string Len = "__len__";
    public const string Type = "__type__";
    public const string CStr = "__str__";
    public const string CBool = "__bool__";
    public const string CFloat = "__float__";
    public const string CInt = "__int__";
    public const string CList = "__list__";
    public const string Copy = "__copy__";
    public const string GetItem = "__getitem__";
    public const string SetItem = "__setitem__";
    public const string Entry = "__entry__";
    public const string Exit = "__exit__";

    public const string Name = "__name__";
    public const string Main = "__main__";

    public const string Run = "run";

    public const string Extension = "un";

    public const char CZero = '0';
    public const char CNine = '9';  

    public const string Bin = "0b";
    public const string Oct = "0o";
    public const string Hex = "0x";

    public const char a = 'a';
    public const char b = 'b';
    public const char e = 'e';
    public const char f = 'f';
    public const char n = 'n';
    public const char o = 'o';
    public const char r = 'r';
    public const char t = 't';
    public const char u = 'u';
    public const char v = 'v';
    public const char x = 'x';

    public const char A = 'A';
    public const char E = 'E';
    public const char F = 'F';
}
